services:
  frontend:
    image: odoo_react/frontend:latest
    build:
      context: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]