services:
  frontend:
    image: odoo_react/frontend:latest
    build:
      context: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
  backend:
    image: odoo:18.0
    ports:
      - "127.0.0.1:8069:8069"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend/addons:/mnt/extra-addons
      - data:/var/lib/odoo
    command: ["odoo", "--dev=reload", "--db-filter=^odoo181$", "--addons-path=/mnt/extra-addons"]
  postgres:
    image: postgres:17
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata
  nginx:
    image: nginx:1.26.1-alpine
    ports:
      - 8080:8080
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    depends_on:
      - backend
configs:
  nginx_config:
    file: ./nginx.conf
volumes:
  data:
  db:
