services:
  flask:
    image: coding_tutorials/flask:latest
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    env_file:
      - ./.env
    environment:
      - DB_PASSWORD