services:
  flask:
    image: coding_tutorials/flask:latest
    build:
      context: flask
      dockerfile: Dockerfile.dev
    ports:
      - 9000:8000
    env_file:
      - ./.env
    environment:
      - DB_PASSWORD
      - FLASK_DEBUG=1
    volumes:
      - ./flask:/app