services:
  flask:
    image: coding_tutorials/flask:latest
    build:
      context: flask
      dockerfile: Dockerfile.dev
    ports:
      - 9000:8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - FLASK_DEBUG=1
    volumes:
      - ./flask:/app
    networks:
      - private
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private

volumes:
  postgres-data:

networks:
  private:
    driver: bridge